### ISSUE TITLE
Make Contest class

### ISSUE THREAD

**Issue by petersont** [judytuna/shortcode-site-309#23]
It looks like we're going to need a context class.

Fields I think the contest class is going to have:

title: the contest itself can have a name, like "PSCC 2011, the HD round"
starting date: the date after which the contest is current
entry deadline: the date the entries will be collected and submitting new render jobs is closed
vote startdate: the date after which voting begins and hence the voting page becomes visible
vote deadline: the date after which voting is closed, and the gallery with winners becomes visible
rules: a string describing the rules of the particular contest
ini: a string containing the contents of the ini file, that's an initialization file for povray
thumbnail ini: one for the thumbnail as well.

Obviously its role in the project will be deeper than that, but first we have to make the class.

**Comment by judytuna** [comment]
It'll have an integer that describes how many characters are allowed (and that will change the shortcode field).

So I did: `rails generate model Contest title:string charlimit:integer startdate:datetime entrydeadline:datetime votingstart:datetime votingend:datetime rules:text ini:text thumbnailini:text`
which resulted in
`invoke  active_record
      create    db/migrate/20111016232224_create_contests.rb
      create    app/models/contest.rb
      invoke    rspec
      create      spec/models/contest_spec.rb
`

A contest has_many entries and votes. An entry and a vote each belongs_to a contest.

Oh man... it will have its own routes based on which contest we're looking at, right?

/contest/1/results will show all the winners of contest 1.

/contest/1/entries/3 could show the entry with id 3 in contest 1, but that's redundant because there will be no other entry with id 3..... oh dear, what have we wrought?... so we'll just keep the contest number out of the URL when we're only viewing one entry at a time. The entry partial (maybe) will display which contest it's in (though this won't be needed if we know we're only looking at a particular contest, so the entry partial isn't the best place for it. I'll keep thinking)

**Comment by judytuna** [comment]
Should there be a web interface for manipulating contests? Then an admin user can add a new "contest minisite" to the big website without having to go in to the console/code. =O

**Comment by petersont** [comment]
Should there be a web interface for manipulating contests?

I think that's a splendid idea.
